### ISSUE TITLE
Redundant loop

### ISSUE THREAD

**Issue by JoaoLages** [khui/repacrr#3]
https://github.com/khui/repacrr/blob/aa5251280455a06314fe6064393649dff60bd496/pred_per_epoch.py#L57

On line 57 you have ` for qid in qid_cwid_pred:` this is a redundant loop as you'll do another loop like this in line 61. Minor bug, but wanted to report it anyway.

**Comment by khui** [comment]
Hi Joao,

Thanks for the report. I will take care of it.

Best,
Kai
