### ISSUE TITLE
More of a doubt than an issue, regarding evaluation

### ISSUE THREAD

**Issue by JoaoLages** [khui/repacrr#4]
Hi there!

I have been trying to understand where do the files under `data/trec_runs/wt**/` come from. I thought they would be an intersection between [this QL submissions from TREC](https://github.com/trec-web/trec-web-2014/tree/master/data/runs/baselines/2014/ql) and the qrel files from that year, but I haven't been able to reproduce what you have.
Maybe I am confused and this files are actually for the RERANK-ALL rather than the RERANK evaluation.

**Comment by andrewyates** [comment]
Yep, these files are actually used by RERANK-ALL. I believe the current cwindri files come from querying the Indri ClueWeb Batch API. To compare against the submitted TREC runs, those runs need to be [downloaded from TREC](http://trec.nist.gov/results.html) and placed in the appropriate directories.

**Comment by JoaoLages** [comment]
Hmm.. What do these files represent then? I thought RERANK-ALL would be the same as RERANK, but for all the submissions of that year. In fact, is the code for RERANK available? As I don't see the QL files for each year.

**Comment by andrewyates** [comment]
Yes, you're right that RERANK-ALL is RERANK over all TREC runs from a given year.

I just looked through the eval code again and realized my last comment was incorrect. If you use the current cwindri files with evals/rerank.py, you should get the RERANK evaluation. If you put the TREC run files in that directory and run rerank.py, you get the RERANK-ALL evaluation.

**Comment by JoaoLages** [comment]
Ok, that's what I understood. So if cwindri gives you RERANK, cwindri are
the QL baseline submissions (from years 12-14), right?

If that's correct, I was searching for the origin of those cwindri QL
submissions, I only find the "indri" ones, from [this link](
https://github.com/trec-web/trec-web-2014/tree/master/data/runs/baselines/2014/ql
).

**Comment by andrewyates** [comment]
Right, cwindri are Indri QL baseline submissions. The source of those cwindri files is the [ClueWeb Batch Query Service](https://lemurproject.org/clueweb09/).

In the PACRR and RE-PACRR papers, however, we used the Terrier QL results from the link you gave. I guess we switched to using cwindri in the repo because we also had those files for 2009-2011.

**Comment by JoaoLages** [comment]
Nice, mystery solved! 
So, just to make sure, can you confirm me if you reported results in the paper using `ql/results-cata.txt` from this [link](https://github.com/trec-web/trec-web-2014/tree/master/data/runs/baselines/2014)? This is from 2014, but the same applies to 2012/13. It's mainly because I want to evaluate in the exact same way and be able to use your previously reported results, so that I don't have to run DUET, DRMM, etc :)

**Comment by andrewyates** [comment]
Yep, that's right!

**Comment by JoaoLages** [comment]
Ok, cool. I will just grab those files, intersect them with the QREL_adhoc
pairs from each respective earl and rerank them :)

I will close the issue, thanks for the clarification!
