### ISSUE TITLE
Context vectors

### ISSUE THREAD

**Issue by alhassan-fadel** [khui/repacrr#9]
Hi all, 
Could you please share the context vectors data to be able to run with context option?

Additionally, in your papers, you haven't mentioned anything about how do you constructed the IDF vectors for each query. I think it is very important for anyone who wants to develop this model to know where or how did you get it. 

Thanks,

**Comment by AbhinavMadahar** [comment]
It's been a while since I worked on this project, so I might be mistaken, but I'm pretty sure that the context vectors are generated by the model based on the input data, so you don't need to download it separately.

**Comment by alhassan-fadel** [comment]
Thanks for your reply
When I run the training script with context option is true I get this error:

File "utils/utils.py", line 470, in load_train_data_generator
    dim_sim=SIM_DIM, max_query_term=MAX_QUERY_LENGTH, n_grams=mat_ngrams, context=CONTEXT)
  File "utils/utils.py", line 151, in convert_cwid_udim_simmat
    pickle.load(open('%s/%s.p' % (contextdir, qid), 'rb')).items()}
IOError: [Errno 2] No such file or directory: '...../PACRR/cosine/context/1.p'

**Comment by andrewyates** [comment]
The IDF vectors are vectors of size |q| containing the IDFs of q's terms [as calculated by Terrier](http://terrier.org/docs/v4.0/javadoc/org/terrier/matching/models/Idf.html#idf(double)) over the document collection. i.e., <IDF(q_1), IDF(q_2), ..., IDF(q_|q|)>

You can find the context vectors [here](https://drive.google.com/open?id=1diW8tpQSDL51934wNlPQ5UjNucU03aus). I don't think this pipeline can generate them right now.

**Comment by alhassan-fadel** [comment]
Thanks so much @andrewyates 
That was very helpful
